name: SurvivalCore
version: ${project.version}
api-version: 1.16
main: fr.iban.survivalcore.SurvivalCorePlugin
authors: [Iban]
description: Core des serveurs en mode survie.
softdepend: [BetterRTP, Warps, BungeeHomes]
depend: [LuckPerms, Essentials, Core, Vault]

commands:
  givetools:
  annonce:
  pvp:
  survivalcore:
  dolphin:
    aliases: [dophin]
